### PR TITLE
Disgoorg master

### PR DESCRIPTION
**Pull request by snekROmonoro**

### CODE REVIEW

**Comment by topi314** [comment]
you know, if there is an issue you can always make a pr with a fix & I'm gonna happily merge it without you needing to hardfork 💀

**Comment by snekROmonoro** [comment]
> you know, if there is an issue you can always make a pr with a fix & I'm gonna happily merge it without you needing to hardfork 💀

yeah ik dw LOL, didn't mean to do this pr, it was done by accident

**Comment by topi314** [comment]
then why are you hard forking and not opening a simple pr with a fix

**Comment by snekROmonoro** [comment]
ig i wanted to hard fork it, idek why i had done it in the past

**Comment by topi314** [comment]
* making those fields `omitempty` is prob completely valid and just an oversight on our side
* adding the actual message data to the error message is valid too and we actually wanted to make that change but just forgot about it
* as for the snowflake changes you want the `"` quotes to be optional so you can also parse number ids from json?

**Comment by snekROmonoro** [comment]
> * as for the snowflake changes you want the `"` quotes to be optional so you can also parse number ids from json?
i remember printing out errors where it failed to parse (valid) snowflakes due to `"` missing

**Comment by topi314** [comment]
then I recommend you open an issue or let us know on our discord so we can look into it instead of doing a yolo

**Comment by snekROmonoro** [comment]
will do in the future 👍🏻

**Pull request closed without merging**
