### PR TITLE
fix `withBearerToken` not working

### PR DESCRIPTION
**Pull request by wnxd**

### CODE REVIEW

**Comment by Skye-31** [comment]
It's worth noting that the check failure is a result of upstream recent commits, not this PR

**Comment by TopiSenpai** [comment]
I fixed dev feel free to pull in

**Review by TopiSenpai — CHANGES_REQUESTED** [review]
the request header is specifically set before applying the opts to allow overriding the header with `WithHeader` or any other opt

maybe it would be better to make `WithToken` set it directly instead of setting `TokenType` & `Token`?

**Comment by TopiSenpai** [comment]
should be good like this
what do you think @wnxd?

**Review by TopiSenpai — APPROVED** [review]

**Comment by TopiSenpai** [comment]
thank you for your contribution

**Comment by wnxd** [comment]
Yeah. Your changes are better.

**Pull request merged**
