### PR TITLE
omit authorization headers where its not needed

### PR DESCRIPTION
**Pull request by TopiSenpai**
send authorization header with bot token only on routes where its needed

### CODE REVIEW

**Comment by TopiSenpai** [comment]
atm on every request the rest client does the bot token is included
this is bad when you use it for your own requests

there are also some endpoints which does not need authorization where we should not send the header

**Comment by Skye-31** [comment]
these routes are ratelimited significantly more strictly without a bot token, this should be a bot option (disabled by default) rather than done for the user

**Comment by TopiSenpai** [comment]
which routes do you mean by these? 🤔

**Comment by Skye-31** [comment]
invite info by code (/api/vX/invites/:code) for example

**Comment by TopiSenpai** [comment]
then we use those with bot token
can you mark which?

**Comment by Skye-31** [comment]
I don't know of all of them, they are undocumented and subject to change at any point. a client option is the safer way to go here than a user's code randomly breaking

**Comment by TopiSenpai** [comment]
or we just use all endpoints with bot token except interaction & webhook 🥲

**Comment by Skye-31** [comment]
that could work fine

**Comment by TopiSenpai** [comment]
should be better now

**Review by Skye-31 — APPROVED** [review]

**Pull request merged**
