### PR TITLE
sharding support

### PR DESCRIPTION
**Pull request by TopiSenpai**

### CODE REVIEW

**Comment by TopiSenpai** [comment]
this is pretty much ready for review/discussion

with the current system you always have a `sharding.ShardManager`

I can think of having either of both on the Bot struct

need ur input on that @Skye-31 :)

**Comment by TopiSenpai** [comment]
The `core.Bot` struct is missing some methods which use `context.Context`

**Comment by Skye-31** [comment]
> this is pretty much ready for review/discussion
> 
> with the current system you always have a `sharding.ShardManager` instead of `gateway.Gateway`
> 
> I can think of having either of both on the Bot struct
> 
> methods using the gateway would be checking which one is used ofc
> 
> need ur input on that @Skye-31 :)

I'd say allow both, and if a sharding manager isn't specified, provide a reasonable default

**Review by Skye-31 — APPROVED** [review]

**Comment by Skye-31** [comment]
Could also be nice to have an option for the time delay between spawning each shard, and the maximum amount of time to wait when a shard is launching before throwing an error

**Comment by TopiSenpai** [comment]
> Could also be nice to have an option for the time delay between spawning each shard, and the maximum amount of time to wait when a shard is launching before throwing an error

for starting a single shard it takes an context & I can add that time to the ratelimiter config 👍🏻

**Comment by TopiSenpai** [comment]
> Could also be nice to have an option for the time delay between spawning each shard

done that :)

**Comment by TopiSenpai** [comment]
what do you think of the init flow via the opts? @Skye-31

**Comment by Skye-31** [comment]
lgtm

**Pull request merged**
