### PR TITLE
payload validation

### PR DESCRIPTION
**Pull request by caneleex**

### CODE REVIEW

**Comment by Malix-off** [comment]
@topi314 is there any log as of why this PR didn't make it?

**Comment by topi314** [comment]
client side payload validation would be a nice thing to have since this would stop bots making wrong requests

but we ultimately decided against it since its a lot of work to get it initially right and no one had the time for it

**Comment by Malix-off** [comment]
@topi314 Understandable.
Do that mean that #44 should be closed as not planned?

**Comment by topi314** [comment]
maybe, maybe not
its still something I'd like to have so I kept it open

**Pull request closed without merging**
